config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/physician'

  get 'home_page/patient'

  get 'home_page/office_worker'

  get 'welcome/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :time_slots

  resources :diagnostic_codes

  resources :appointments

  resources :physicians

  resources :patients

  resources :appointments do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :patients do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :diagnostic_codes do
    collection { post :import }
  end

   root 'welcome#index'

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
  has_many :patients, through: :appointments

  validates_uniqueness_of :id, :scope => [:start_time, :end_time]

  def parsedStartTime
    "#{start_time.strftime("%H:%M%p")} - #{end_time.strftime("%H:%M%p")}"
  end


  validate :chk_time_slot_before_8am
  validate :chk_slot_time_30_min
  validate :chk_time_slot_after_4_30pm



  def chk_slot_time_30_min
    if (start_time.min - end_time.min) != 30
      errors.add( :end_time, "for appointment has to be 30 min after the appointment start time")
    end
  end

  def getMin(time)
    return((time.hour*60) + time.min)
  end

  def chk_time_slot_before_8am
    begin_t = Time.parse("7:59am")

    t_start_time = Time.parse(start_time.to_s)

    if (getMin(t_start_time) < getMin(begin_t))
      errors.add(:start_time, "cannot be before 8:00AM.")
    end
  end

  def chk_time_slot_after_4_30pm

    end_t = Time.parse("4:32pm")

    t_end_time = Time.parse(end_time.to_s)

    if  (getMin(t_end_time) > getMin(end_t))
      errors.add(:end_time, "cannot be after 4:30PM.")
    end
  end

end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @time_slots = TimeSlot.all
    respond_with(@time_slots)
  end

  def show
    respond_with(@time_slot)
  end

  def new
    @time_slot = TimeSlot.new
    respond_with(@time_slot)
  end

  def edit
  end

  def create
    @time_slot = TimeSlot.new(time_slot_params)
    @time_slot.save
    respond_with(@time_slot)
  end

  def update
    @time_slot.update(time_slot_params)
    respond_with(@time_slot)
  end

  def destroy
    @time_slot.destroy
    respond_with(@time_slot)
  end

  private
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    def time_slot_params
      params.require(:time_slot).permit(:start_time, :end_time)
    end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time, :ampm => true%>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time, :ampm => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing time slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<h1>Listing time slots</h1>

<table class="table">
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.start_time.strftime("%H:%M%p") %></td>
        <td><%= time_slot.end_time.strftime("%H:%M%p") %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time slot', new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New time slot</h1>

<%= render 'form' %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @time_slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @time_slot.end_time %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>