config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/physician'

  get 'home_page/patient'

  get 'home_page/office_worker'

  get 'welcome/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :time_slots

  resources :diagnostic_codes

  resources :appointments

  resources :physicians

  resources :patients

  resources :appointments do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :patients do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :diagnostic_codes do
    collection { post :import }
  end

   root 'welcome#index'

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
  STATUS_TYPES = ["Active", "Inactive"]


end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name, :status, :address, :phone)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select(:status, Physician::STATUS_TYPES) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h3>Listing physicians</h3>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= physician.address %></td>
        <td><%= number_to_phone(physician.phone) %></td>
        <td><%= physician.status %></td>
        
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physician.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @physician.address %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @physician.phone %>
</p>
<p>
  <strong>Status:</strong>
  <%= @physician.status %>
</p>

<strong>Appointments:</strong>
<table  class="table">
  <thead>
  <tr>
    <th>Patient</th>
    <th>Appointment reason</th>

    <th>Appointment Date</th>
    <th>Time Slot</th>
    <th>Appointment status</th>
    <th>Physician note</th>
    <th>Fee</th>
    <th>Diagnostic code</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @physician.appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.name %></td>


        <td><%= appointment.appointment_reason %></td>

        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.time_slot.start_time.strftime("%a %H:%M%p - ") %>
          <%= appointment.time_slot.end_time.strftime("%H:%M%p") %>
        <td><%= appointment.appointment_status %></td>
        <td><%= appointment.physician_note %></td>

        <td><%= number_to_currency(appointment.fee, unit: "$") %></td>
        <td><%= appointment.diagnostic_code.dermatology_code %></td>
        </td>


        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>