config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/physician'

  get 'home_page/patient'

  get 'home_page/office_worker'

  get 'welcome/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :time_slots

  resources :diagnostic_codes

  resources :appointments

  resources :physicians

  resources :patients

  resources :appointments do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :patients do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :diagnostic_codes do
    collection { post :import }
  end

   root 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments

  before_destroy :chk_no_appointment_cancel_8hr

  def getMin(time)
    return((time.hour*60) + time.min)
  end

  def chk_no_appointment_cancel_8hr
    Time.zone = 'Central Time (US & Canada)'
    s_time = getMin(self.appointments.time_slot.start_time - Time.zone.now)
    if self.appointments.appointment_date == Date.today() and s_time < (8.hour * 60)
      errors.add(:start_time, "is less than 8 hours before appointment. Contact dermatology office to cancel.")
    end
  end


end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @appointments = Appointment.all
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def patient_show
    @appointment = Appointment.find(params[:id])
    @patient = Patient.find(params[:id])

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :address, :phone)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
    <div class="field">
      <%= f.label :phone %><br>

      <%= f.text_field :phone %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h3>Listing patients</h3>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.address %></td>
        <td><%= number_to_phone(patient.phone) %></td>

        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<table  class="table">
  <thead>
  <tr>

    <th>Physician</th>


    <th>Appointment reason</th>

    <th>Appointment Date</th>
    <th>Time Slot</th>
    <th>Appointment status</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @patient.appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.physician.name %></td>

        <td><%= appointment.appointment_reason %></td>

        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.time_slot.start_time.strftime("%a %H:%M%p - ") %>
          <%= appointment.time_slot.end_time.strftime("%H:%M%p") %>
        <td><%= appointment.appointment_status %></td>

        </td>



        <td><%= link_to 'Cancel', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Appointment', new_appointment_path %>

</br>
<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>