config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/physician'

  get 'home_page/patient'

  get 'home_page/office_worker'

  get 'welcome/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :time_slots

  resources :diagnostic_codes

  resources :appointments

  resources :physicians

  resources :patients

  resources :appointments do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :patients do
    member do
      post :patient_index
      get 'patient_index'
      post :save_patient_index
      get 'save_patient_index'
      post :patient_show
      get 'patient_show'
    end
  end

  resources :diagnostic_codes do
    collection { post :import }
  end

   root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient
  belongs_to :diagnostic_code
  belongs_to :time_slot
  STATUS_TYPES = ["Pending", "Completed", "Cancelled", "Patient did not show"]

  validates_presence_of :appointment_date
  validates_uniqueness_of :time_slot_id, :scope => [:appointment_date, :physician_id]
  validate :chk_appointment_date_greater_than_today
  validate :chk_appointment_day_not_sat_sun
  before_destroy :chk_no_appointment_cancel_8hr




  def chk_no_appointment_cancel_8hr

    s_time = Time.now - self.time_slot.start_time
    if (self.appointment_date <= Date.today) and s_time < 8
      errors.add(:start_time, "is less than 8 hours before appointment. Contact dermatology office to cancel.")
    end
  end


def chk_appointment_date_greater_than_today
  if self.appointment_date < Date.today.end_of_day
    errors.add(:appointment_date, "cannot be today or before today.")
  end
end

  def chk_appointment_day_not_sat_sun
    #check so that appointment is not on Sat or Sun
    app_day = self.appointment_date.strftime("%a")
    check_day = self.appointment_date.wday
    if check_day == 0 or check_day == 6
      errors.add(:appointment_date,"you selected is #{app_day}. No appointments on Sat or Sun.")
    end
  end





end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @appointments = Appointment.all
    respond_with(@appointments)
  end

  def show
    respond_with(@appointment)
  end

  def new
    @appointment = Appointment.new
    respond_with(@appointment)
  end

  def edit
  end


  def create

    @appointment = Appointment.new(appointment_params)
    @appointment.save
    respond_with(@appointment)
  end

  def update
    @appointment.update(appointment_params)
    respond_with(@appointment)
  end

  def destroy
    @appointment.destroy
    respond_with(@appointment)
  end

  def patient_show
    @appointment = Appointment.find(params[:id])
    @patient = Patient.find(params[:id])
    respond_with(@appointment)
  end

  def patient_index
    @patients = Patient.all
    @appointment = Appointment.find(params[:id])
    respond_with(@appointment)
    @appointment = Appointment.new(appointment_params)
    @appointment.save
    respond_with(@appointment)
  end

  def save_patient_index

    @appointment = Appointment.new(appointment_params)
    @appointment.save
    respond_with(@appointment)
  end


  private


    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:patient_id, :physician_id, :diagnostic_code_id, :appointment_reason, :appointment_status, :physician_note, :fee, :time_slot_id, :appointment_date)
    end


end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container-fluid">
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id, Patient.all,:id, :name %>
  </div>
  <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id, Physician.all,:id, :name %>
  </div>
  <div class="field">
    <%= f.label :appointment_date %><br>
    <%= f.date_select :appointment_date,:start_year => Date.today.year, :end_year => Date.today.year + 1, :start_day => Date.today, order: [:month , :day , :year] %>
  </div>
    <div class="field">
      <%= f.label :time_slot_id %><br>

      <%= f.collection_select :time_slot_id, TimeSlot.all,:id, :parsedStartTime%>
    </div>
    <div class="field">
    <%= f.label :appointment_reason %><br>
    <%= f.text_area :appointment_reason %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


  </br>

  <hr>
  <p>Fields below to be filled by physician.</p>
  <div class="field">
    <%= f.label :physician_note %><br>
    <%= f.text_area :physician_note %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>

  <div class="field">
    <%= f.label :diagnostic_code_id %><br>
    <%= f.collection_select :diagnostic_code_id, DiagnosticCode.all,:id, :dermatology_code %>
  </div>
  <div class="field">
    <%= f.label :appointment_status %><br>
    <%= f.select(:appointment_status, Appointment::STATUS_TYPES) %>
  </div>

</div>
<% end %>

app/views/appointments/_form_1.html.erb
<%= form_for(@appointment) do |f| %>
    <% if @appointment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

          <ul>
            <% @appointment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="container-fluid">
      <div class="field">
        <%= f.label :patient_id %><br>
        <%= f.collection_select :patient_id, Patient.all,:id, :name %>
      </div>
      <div class="field">
        <%= f.label :physician_id %><br>
        <%= f.collection_select :physician_id, Physician.all,:id, :name %>
      </div>
      <div class="field">
        <%= f.label :appointment_date %><br>
        <%= f.date_select :appointment_date,:start_year => Date.today.year, :end_year => Date.today.year + 1, :start_day => Date.today, order: [:month , :day , :year] %>
      </div>
      <div class="field">
        <%= f.label :time_slot_id %><br>

        <%= f.collection_select :time_slot_id, TimeSlot.all,:id, :parsedStartTime%>
      </div>
      <div class="field">
        <%= f.label :appointment_reason %><br>
        <%= f.text_field :appointment_reason %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h3>Listing appointments</h3>

<table  class="table">
  <thead>
    <tr>
      <th>Patient</th>
      <th>Physician</th>


      <th>Appointment reason</th>

      <th>Appointment Date</th>
      <th>Time Slot</th>

      <th>Physician note</th>
      <th>Fee</th>
      <th>Diagnostic code</th>
      <th>Appointment status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.physician.name %></td>

        <td><%= appointment.appointment_reason %></td>

        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.time_slot.start_time.strftime("%a %H:%M%p - ") %>
          <%= appointment.time_slot.end_time.strftime("%H:%M%p") %>

        <td><%= appointment.physician_note %></td>
        <td><%= number_to_currency(appointment.fee, unit: "$") %></td>
        <td><%= appointment.diagnostic_code.dermatology_code %></td>
        <td><%= appointment.appointment_status %></td>
        </td>


        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointments</h1>


<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/patient_index.html.erb
<%= render 'form_1' %>
<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/appointments/patient_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<table  class="table">
  <thead>
  <tr>
    <th>Patient</th>
    <th>Physician</th>


    <th>Appointment reason</th>

    <th>Appointment Date</th>
    <th>Time Slot</th>
    <th>Appointment status</th>
    <th>Physician note</th>
    <th>Fee</th>
    <th>Diagnostic code</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.physician.name %></td>

        <td><%= appointment.appointment_reason %></td>

        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.time_slot.start_time.strftime("%a %H:%M%p - ") %>
          <%= appointment.time_slot.end_time.strftime("%H:%M%p") %>
        <td><%= appointment.appointment_status %></td>
        <td><%= appointment.physician_note %></td>
        <td><%= appointment.fee %></td>
        <td><%= appointment.diagnostic_code.dermatology_code %></td>
        </td>


        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patient_index_appointment_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.name %>
</p>

<p>
<p>
  <strong>Appointment Date:</strong>
  <%= @appointment.appointment_date %>
</p>
<p>
  <strong>Time Slot:</strong>
  <%= @appointment.time_slot.start_time.strftime("%H:%M%p") %> -
  <%= @appointment.time_slot.end_time.strftime("%H:%M%p") %>
</p>

<p>
  <strong>Appointment reason:</strong>
  <%= @appointment.appointment_reason %>
</p>

<p>
  <strong>Appointment status:</strong>
  <%= @appointment.appointment_status %>
</p>

<p>
  <strong>Physician note:</strong>
  <%= @appointment.physician_note %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @appointment.fee %>
</p>
<strong>Diagnostic code:</strong>
<%= @appointment.diagnostic_code.dermatology_code %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', patients_path %>